#!/usr/bin/env bash
# Re-runnable connectivity smoke test
# Generated by .claude/scripts/run-smoke-test.js. Do not commit credentials.
# Usage: ( set -a; . web/.env.local; set +a; bash generated-docs/specs/api-smoke-test.sh )
set -u
BASE_URL="http://localhost:10010"
curl \
  -sS \
  -o \
  /tmp/smoke-body \
  -w \
  "%{http_code}\n" \
  "$BASE_URL/v1/health"
